version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "aws-angular-hello-world"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    pre_build:
        commands:
            - echo running unit test cases
            - ng test --watch=false --browsers PhantomJS
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 rm s3://${S3_BUCKET}/*
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build Completed on `date`
artifacts:
    files:
        - '*'
    base-directory: 'dist*'
    discard-paths: yes